services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
    env_file:
      - .env
    depends_on:
      - redis
      - qdrant

  bizartvisor-fe:
    build: ./bizartvisor-fe
    ports:
      - "3000:3000"
    depends_on:
      - server

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant_data
      
volumes:
    redis_data:
    qdrant:
